language: python
python:
  - "3.5"
  - "3.6"

# Python 3.7+ has to be done a different way
# https://github.com/travis-ci/travis-ci/issues/9069
jobs:
  include:
    - language: python
      python: "3.7"
      dist: xenial
      sudo: required
    - language: python
      python: "3.8-dev"
      dist: xenial
      sudo: required

# Allow some newer versions of Python to fail for now
# This will be changed once the required packages starts
# supporting the newer versions of Python:
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"

install:
  - pip install --upgrade pip
  - pip uninstall numpy Bottleneck -y
  - pip install -r requirements.txt --no-cache-dir
  - python -c "from photometry.spice import TESS_SPICE; print(TESS_SPICE())"
script:
  - pytest
branches:
  only:
    - master
    - devel
    - /^v\d+\.\d+.+$/

# Deploy to GitHub Releases, making a release of the
# code whenever a new tag is added on the master branch
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  draft: true
  on:
    branch:
      - master
      - /^v\d+\.\d+.+$/
    tags: true
