language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# Disabled because of https://github.com/travis-ci/travis-ci/issues/9069
jobs:
  include:
    - language: python
      python: "3.7"
      dist: xenial
      sudo: required

install:
  - pip install -r requirements.txt
script:
  - pytest
branches:
  only:
    - master
    - devel
